[package]
name = "sbtui"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Terminal UI sing-box proxy client"

[dependencies]
anyhow = "1.0.99"
client-core = { path = "../client-core" }
base64 = "0.22.1"
clap = { version = "4.5.48", features = ["derive"] }
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures-util = "0.3.31"
ratatui = "0.29.0"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros", "time"] }


[dev-dependencies]
insta = "1.43.2"
tempfile = "3.23.0"
